### ISSUE TITLE
Can not see public classes after add library

### ISSUE THREAD

**Issue by meghdadfm** [centrifugal/centrifuge-java#36]
Hello,
I added this line to gradle
   implementation 'io.github.centrifugal:centrifuge-java:0.2.0'
library added successfully. Also I add this line of code manually at top of my class
   import io.github.centrifugal.centrifuge.* 
but I can not see the public classes like Client. EventListener or other public classes.

what should I do ?

**Comment by FZambia** [comment]
Was able to reproduce with 0.2.0. Release [0.2.2](https://github.com/centrifugal/centrifuge-java/releases/tag/0.2.2) which should work OK (the problem gone away for me with it).

The reason was that I removed classifiers from build.gradle in 0.2.0 because they were marked deprecated by Android Studio. Seems that they affect build in some way. So I put them back in https://github.com/centrifugal/centrifuge-java/commit/27374a90a6ab9fa9c2f565c4f205eddafac30427 and released 0.2.2
