### ISSUE TITLE
Consider using minifuture instead of cfuture

### ISSUE THREAD

**Issue by vyndor** [centrifugal/centrifuge-java#66]
I suggest start using of [Minifuture](https://github.com/stefan-zobel/minifuture) instead of streamsupport-cfuture because it is more compact.

I can create PR if you agree.

**Comment by FZambia** [comment]
Hello @vyndor 

Many thanks for a suggestion, I have a couple of questions:

1. Do you know whether it will make a noticeable difference? I suppose since we are depending on Protobuf - it may come with much bigger overhead than `cfuture`. I can be wrong though.
2. Did you use `minifuture` in other projects? It seems like a lib maintained by the same author as `cfuture` but I personally not very close to Java ecosystem so need some judgement here about `minifuture` in real world.

**Comment by FZambia** [comment]
> Our project has an indirect dependency on minifuture and I had a name conflict when tried to add dependency to centrifuge.

I afraid that if centrifuge-java will switch to `minifuture` then the same can happen for users who already using `cfuture` in their projects 🤔 I suppose we need to test this case – if it won't result into issues, then it seems good to go.
